#!/bin/sh
set -e
umask 022
LANG=C
export LANG

nomd5=0
notime=0
noowner=0
nogroup=0

while [ $# -gt 0 ]; do
    case "$1" in
    --help|--usage)
        (
            echo "usage: findls [options ...] [find options ...]"
            echo "options:"
            echo "    --no-md5"
            echo "    --no-time"
            echo "    --no-owner (or --no-user)"
            echo "    --no-group "
        ) 1>&2
        exit 0
        ;;
    --no-md5|--nomd5)
        nomd5=1
        shift
        ;;
    --no-time|--notime)
        notime=1
        shift
        ;;
    --no-owner|--noowner|--no-user|--nouser)
        noowner=1
        shift
        ;;
    --no-group|--nogroup)
        nogroup=1
        shift
        ;;
    *)
        break
        ;;
    esac
done
[ $# -gt 0 ] || set -- .

find "$@" \
| sort -u \
| while read file; do
    ls -ld --time-style=full-iso "$file"
done \
| while read mode link owner group size ymd hms off path; do

    [ "$noowner" -eq 0 ] || owner='-'
    [ "$nogroup" -eq 0 ] || group='-'

    if [ "$notime" -ne 0 ]; then
        ymd='0000-00-00'
        hms='00:00:00.000000000'
        off='+0000'
    fi
    md5='-'
    case "$mode" in
    d*|l*)
        size='-'
        ymd='0000-00-00'
        hms='00:00:00.000000000'
        off='+0000'
        ;;
    -*)
        if [ "$nomd5" -eq 0 ]; then
            md5=$(md5sum "$path")
            md5=${md5%% *}
        fi
        ;;
    esac
    echo "$mode $owner $group $size ${ymd}+${hms}$off $md5 $path"
done

exit 0
