#!/bin/sh
ps uxwwe | while read line; do
    for i in $line; do
        case "$i" in
        SSH_AGENT_PID=*) echo "export $i" ;;
        SSH_AUTH_SOCK=*) echo "export $i" ;;
        esac
    done
done | sort -u
